[package]
name = "aoc2022"
version = "0.1.0"
authors = ["Callum Ward <wards.callum@gmail.com>"]
edition = "2021"
default-run="08"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
